### ISSUE TITLE
[Request] Script to hide leaderboard spam / show only your own scores?

### ISSUE THREAD

**Issue by bigger0gamer** [jakubtomsu/mineparkour-club-hax#2]
Thanks to your "finish instantly repreatedly" script (not that I blame you, you're not the first person to make and release hacks), playing on the site has gotten obnoxious from middle schoolers who think flooding the leaderboard is funny. Its gotten hard to see my times when I'm doing speedruns on the site, and I wonder if it would be possible to hide times from the leaderboard somehow. A simple and effective way to get spam off the leaderboard would be to hide any times that aren't from you or match your nickname (and TBH, would be nice to not have to see slurs and racism from the same middle schoolers with zero maturity, even if it doesn't show up often), but IDK enough about javascript and stuff myself to find the appropriate methods that handles receiving scores from the server (and main.js being optimized / obfuscated isn't helpful either >.>). You wouldn't happen to be able to do that? Or at least give a few pointers if you can't be bothered.

**Comment by jakubtomsu** [comment]
Wow, I totally forgot to check this repo for a long time, sorry for no response!

I think it's totally possible to hide the leaderboard, I'm gonna look into it tommorow.

**Comment by jakubtomsu** [comment]
(this is just an quick fix, there should be a way to remove everyone except you from the leaderboard)

**You can disable the whole leaderboard with this:**
```js
leaderboardVisual.opacity = 0
```

**Comment by jakubtomsu** [comment]
seems like @Rengaf05 figured out some stuff, check out [cleaup_leaderboard.js](/jakubtomsu/mineparkour-club-hax/blob/main/cleanup_leaderboard.js) etc

**Comment by Rengaf05** [comment]
Ok after some work it's finished. There are 3 new files: hide_leaderboard.js, cleanup_leaderboard.js and cleanup_leaderboard_with_reposition.js.

### hide_leaderboard.js
This file is what @jakubtomsu responded with, just in file

### cleanup_leaderboard.js
This will remove all names in the leaderboard except for name in variable `myname` (I could not find a reference of own name in the code, so you have to specify it)

### cleanup_leaderboard_with_reposition.js
And the masterpiece. This will remove the names and put them in place, but because mineparkour club is the BEST game ever made it might sometimes collapse into each other. That's why I put this code into another file

**Comment by bigger0gamer** [comment]
This looks awesome. Thanks so much for making it! I'll have to give this a shot!

**Comment by bigger0gamer** [comment]
I gave cleanup_leaderboard_with_reposition.js a shot, and it works like a charm! I was able to find a reference for your own name to improve it however: `document.getElementById('nickname').value`. I can understand why you might have missed that though, since I couldn't find any reference (that worked) in any of the javascript itself.

The code isn't perfect, since the height of the leaderboard still shows all times, and it occasionally flickers the full leaderboard, but it don't bother me none. I was able to work it into a tampermonkey script, so this will super handy for when people spam the leaderboard. Thank you so much!

**Comment by jakubtomsu** [comment]
> The code isn't perfect, since the height of the leaderboard still shows all times

you could use this to disable the leaderboard background, if that's what you meant:
```js
leaderboardVisual.belowObjects.at(0).opacity = 0;
```

**Comment by Rengaf05** [comment]
Ok ty @bigger0gamer for your contribution. And for the flickers. The problem is that we don't know where the information for `leaderboardVisual` comes from (maybe it comes from nowhere and is generated each second). However what we can do (instead of going through the obfuscated main.js) is that we can try to be faster than the game. In our case using `setTimeout`. So we aren't changing anything we just overwrite it really fast
